/**
 * This class is generated by jOOQ
 */
package com.galiamov.mailrepository.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRepository extends SchemaImpl {

	private static final long serialVersionUID = 1296942944;

	/**
	 * The reference instance of <code>email_repository</code>
	 */
	public static final EmailRepository EMAIL_REPOSITORY = new EmailRepository();

	/**
	 * No further instances allowed
	 */
	private EmailRepository() {
		super("email_repository");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			com.galiamov.mailrepository.db.tables.EmailRepository.EMAIL_REPOSITORY);
	}
}
