/**
 * This class is generated by jOOQ
 */
package com.galiamov.mailrepository.db;


import com.galiamov.mailrepository.db.tables.EmailRepository;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in email_repository
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table email_repository.email_repository
	 */
	public static final EmailRepository EMAIL_REPOSITORY = com.galiamov.mailrepository.db.tables.EmailRepository.EMAIL_REPOSITORY;
}
